module.exports={especialidadesjson:[
  "Alergología",
"Anestesiología",
"Aparato digestivo",
"Cardiología",
"Endocrinología y nutrición",
"Geriatría",
"Hematología y hemoterapia",
"Medicina de la educación física y del deporte",
"Nefrología",
"Neumología",
"Neurología",
"Neurofisiología Clínica",
"Oncología médica",
"Oncología radioterápica",
"Pediatría",
"Psiquiatría",
"Rehabilitación",
"Reumatología",
"Cirugía cardiovascular",
"Cirugía general y del aparato digestivo",
"Cirugía oral y maxilofacial",
"Cirugía ortopédica y traumatología",
"Cirugía pediátrica",
"Cirugía plástica estética y reparadora",
"Cirugía torácica",
"Neurocirugía",
"Angiología y cirugía vascular",
"Dermatología médico-quirúrgica y venereología",
"Obstetricia y ginecología",
"Oftalmología",
"Otorrinolaringología",
"Urología",
"Análisis clínicos",
"Anatomía patológica",
"Bioquímica clínica",
"Farmacología clínica",
"Inmunología",
"Medicina nuclear",
"Microbiología y parasitología",
"Neurofisiología clínica",
"Radiodiagnóstico"
]}
